name: GitLab Runner
on:
  workflow_dispatch:
    inputs:
      max-builds:
        type: number
        description: "Maximum number of builds to run"
        required: false
        default: "1"

permissions: {}

jobs:
  gitlab-runner:
    name: GitLab Runner
    runs-on: ubuntu-latest
    container:
      image: gitlab/gitlab-runner:v19.2.0
      options: --privileged
    steps:
      - name: Run single
        env:
          CI_SERVER_URL: ${{ secrets.GITLAB_RUNNER_URL }}
          CI_SERVER_TOKEN: ${{ secrets.GITLAB_RUNNER_TOKEN }}
          RUNNER_EXECUTOR: docker
          DOCKER_IMAGE: alpine
          DOCKER_VOLUMES: /certs/client:/certs/client
          DOCKER_PRIVILEGED: true
          RUNNER_ENV: DOCKER_TLS_CERTDIR=/certs
          MAX_BUILDS: ${{ github.event.inputs.max-builds }}
        run: |
          gitlab-runner run-single --max-builds ${MAX_BUILDS} > /dev/null 2>&1
